import Head from "next/head";
import Avatar from "../components/Avatar";
import { ViewGridIcon } from "@heroicons/react/solid";
import { SearchIcon } from "@heroicons/react/outline";
import Image from "next/image";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        {/* Left Section */}
        <div className="flex space-x-4 items-center"></div>

        {/* Right Section */}
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>

          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-200 cursor-pointer" />

          <Avatar url="/assets/avatar.jpg" />
        </div>
      </header>

      {/* Body */}
      <form className="flex flex-col items-center  mt-[4rem] flex-grow w-4/5">
        <Image src="/assets/Google.svg" height={100} width={300} />

        <div className="flex w-full mt-5 hover:shadow-lg rounded-full focus-within:shadow-lg max-w-md border border-gray-200 px-4 py-2 items-center sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-4 mr-3 text-gray-400" />
          <input type="text" className="focus:outline-none flex-grow" />
          <Image
            src="/assets/Google_Mic.svg"
            height={20}
            width={20}
            className="cursor-pointer"
          />
        </div>

        <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4 ">
          <button className="btn">Google Search</button>
          <button className="btn">I'm Feeling Lucky</button>
        </div>
      </form>

      {/* Footer */}
      <Footer />
    </div>
  );
}
